package hkmc2
package codegen

import utils.*
import hkmc2.Message.MessageContext

import scala.collection.mutable.HashMap
import scala.util.chaining.*

import mlscript.utils.*, shorthands.*

import semantics.*
import semantics.Elaborator.{State, Ctx, ctx}

import syntax.{Literal, Tree}
import hkmc2.syntax.Tree.Ident

// it should be possible to cache some common constructions (End, Option) into the context
// this avoids having to rebuild the same shapes everytime they are needed
// allowMultipleParamList: bypasses error from instrumenting user functions with multiple parameter lists
case class Context(cache: HashMap[Path | Symbol, Path], allowMultipleParamList: Bool = false):
  def getCache(p: Path | Symbol): Option[Path] = cache.get(p)
  def addCache(p: Path | Symbol, v: Path): Context = Context(cache.clone() += (p -> v), allowMultipleParamList)
  def delCache(p: Path | Symbol): Context = Context(cache.clone() -= p, allowMultipleParamList)

extension [A, B](ls: Iterable[(A => B) => B])
  def collectApply(f: Ls[A] => B): B =
    // defer applying k while prepending new elements to the list
    ls.foldRight((_: Ls[A] => B)(Nil))((headCont, tailCont) =>
      k =>
        headCont: head =>
          tailCont: tail =>
            k(head :: tail),
    )(f)

extension [A](xs: Ls[Context => ((A, Context) => Block) => Block])
  def chainContext(using ctx: Context)(k: (Ls[A], Context) => Block): Block =
    xs.foldRight((ctx: Context) => (k: (Ls[A], Context) => Block) => k(Nil, ctx))((head, tail) =>
      ctx =>
        k =>
          head(ctx): (head, ctx) =>
            tail(ctx): (tail, ctx) =>
              k(head :: tail, ctx),
    )(ctx)(k)

type ArgWrappable = Path | Symbol

def asArg(x: ArgWrappable): Arg = x match
  case p: Path => p.asArg
  case l: Symbol => l.asPath.asArg

// null and undefined are missing
def toValue(lit: Str | Int | BigDecimal | Bool): Value =
  val l = lit match
    case i: Int => Tree.IntLit(i)
    case b: Bool => Tree.BoolLit(b)
    case s: Str => Tree.StrLit(s)
    case n: BigDecimal => Tree.DecLit(n)
  Value.Lit(l)

// transform Block to Block IR so that it can be instrumented in mlscript
class ReflectionInstrumenter(using State, Raise, Ctx) extends BlockTransformer(SymbolSubst.Id):
  // TODO: there could be a fresh scope per function body, instead of a single one for the entire program
  val scope = Scope.empty(Scope.Cfg.default)
  // recover `defn` for when `sym.defn` is `None`, when the definition was generated by other compiler passes
  val defnMap = HashMap[Symbol, ClsLikeDefn | ClsLikeBody]()
  var symbolMapSym: Opt[Symbol] = N
  
  // helpers for constructing Block

  def assign(res: Result, symName: Str = "tmp")(k: Path => Block): Block =
    // TODO: skip assignment if res: Path?
    val sym = new TempSymbol(N, symName)
    Scoped(Set(sym), Assign(sym, res, k(sym.asPath)))

  def tuple(elems: Ls[ArgWrappable], symName: Str = "tmp")(k: Path => Block): Block =
    assign(Tuple(false, elems.map(asArg)), symName)(k)

  def ctor(cls: Path, args: Ls[ArgWrappable], symName: Str = "tmp")(k: Path => Block): Block =
    assign(Instantiate(false, cls, args.map(asArg)), symName)(k)

  def call(fun: Path, args: Ls[ArgWrappable], isMlsFun: Bool = true, symName: Str = "tmp")(k: Path => Block): Block =
    assign(Call(fun, args.map(asArg))(isMlsFun, false, false), symName)(k)

  // helpers for constructing Block IR

  def blockMod(name: Str) = summon[State].blockSymbol.asPath.selSN(name)
  def optionMod(name: Str) = summon[State].optionSymbol.asPath.selSN(name)
  def helperMod(name: Str) = summon[State].specializeHelpersSymbol.asPath.selSN(name)

  def blockCtor(name: Str, args: Ls[ArgWrappable], symName: Str = "tmp")(k: Path => Block): Block =
    call(blockMod(name), args, true, symName)(k)
  def optionSome(arg: ArgWrappable, symName: Str = "tmp")(k: Path => Block): Block =
    call(optionMod("Some"), Ls(arg), true, symName)(k)
  def optionNone(symName: Str = "tmp")(k: Path => Block): Block =
    assign(optionMod("None"), symName)(k)

  def blockCall(name: Str, args: Ls[ArgWrappable], symName: Str = "tmp")(k: Path => Block): Block =
    call(blockMod(name), args, symName = symName)(k)

  // linking functions defined in MLscipt

  def fnPrintCode(p: Path)(k: Block): Block =
    val printCodeFun = blockMod("Printer").selSN("class").selSN("default").selSN("printCode")
    // discard result, we only care about side effect
    call(printCodeFun, Ls(p))(_ => k)

  def fnConcat(p1: Path, p2: Path, symName: String = "concat")(k: Path => Block): Block =
    blockCall("concat", Ls(p1, p2), symName)(k)

  // transformation helpers

  // preserveName overrides the renaming of symbols within the function
  // if sym is ClassSymbol, we may need pOpt to link to the path pointing to the value of the symbol
  def transformSymbol(sym: Symbol, preserveName: Bool = false, pOpt: Option[Path] = N, symName: Str = "sym")(using stagingCtx: Context)(k: (Path, Context) => Block): Block =
    def cachedK(p: Path, ctx: Context) =
      k(p, ctx.addCache(sym, p))
    def checkMap(mapType: Str, key: Path, p: Path, ctx: Context) =
      if symbolMapSym is None then symbolMapSym = S(TempSymbol(N, "symbolMap"))
      call(symbolMapSym.get.asPath.selSN("checkMap"), Ls(toValue(mapType), key, p))(cachedK(_, ctx))
      // blockCall("checkMap", Ls(symbolMapSym.get, key, p))(cachedK(_, ctx))
    stagingCtx.getCache(sym).map(cachedK(_, stagingCtx)).getOrElse:
      // add name to scope to avoid shadowing by other symbols
      val newName = scope.allocateOrGetName(sym)
      val rename = sym match
        case _ if preserveName => false
        // avoid name collision
        case _: TempSymbol | _: VarSymbol => true
        // FIXME: there may be more types of symbols that need to be renamed during staging
        case _: BaseTypeSymbol | _: BuiltinSymbol => false
        case t: TermSymbol if t.defn.exists(_.sym.asTrm.isDefined) && (t.k is syntax.Fun) => false
        case _ => false
      val name = if rename then newName else sym.nme
      // println(("symbol:", sym, name, stagingCtx))
      sym match
        case t: TermSymbol if t.defn.exists(_.sym.asClsOrMod.isDefined) =>
          // no need to perform caching for redirecting call
          transformSymbol(t.defn.get.sym.asClsOrMod.get, rename, pOpt, symName)(k)
        case _: NoSymbol =>
          blockCtor("NoSymbol", Nil, symName)(cachedK(_, stagingCtx))
        case clsSym: ClassSymbol if ctx.builtins.virtualClasses(clsSym) =>
          blockCtor("VirtualClassSymbol", Ls(toValue(name)), symName)(checkMap("classMap", toValue(name), _, stagingCtx))
        case baseSym: BaseTypeSymbol =>
          val (owner, bsym, paramsOpt, auxParams) = (baseSym.defn, defnMap.get(baseSym)) match
            case (S(defn), _) => (defn.owner, defn.bsym, defn.paramsOpt, defn.auxParams)
            case (_, S(defn: ClsLikeDefn)) => (defn.owner, defn.sym, defn.paramsOpt, defn.auxParams)
            // FIXME: hack to patch in staging for returning the object Unit.
            case _ if baseSym == State.unitSymbol => (N, baseSym, N, Nil)
            case _ =>
              raise(ErrorReport(msg"Unable to infer parameters from symbol in staged module, which are necessary to reconstruct class instances: ${sym.toString()}" -> sym.toLoc :: Nil))
              return End()
          
          val path = pOpt.getOrElse(owner match
            case S(owner) => owner.asPath.selSN(baseSym.nme)
            case N => bsym.asPath)
          
          baseSym match
            case _: ClassSymbol =>
              transformParamsOpt(paramsOpt): (paramsOpt, ctx) =>
                auxParams.map(ps => ctx => transformParamList(ps)(using ctx)).chainContext: (auxParams, ctx) =>
                  tuple(auxParams): auxParams =>
                    blockCtor("ConcreteClassSymbol", Ls(toValue(name), path, paramsOpt, auxParams), symName)(checkMap("classMap", path, _, ctx))
            case _: ModuleOrObjectSymbol =>
              blockCtor("ModuleSymbol", Ls(toValue(name), path), symName)(checkMap("moduleMap", path, _, stagingCtx))
        case _ =>
          blockCtor("Symbol", Ls(toValue(name)), symName)(cachedK(_, stagingCtx))

  def transformOption[A](xOpt: Opt[A], f: A => ((Path, Context) => Block) => Block)(using Context)(k: (Path, Context) => Block): Block = xOpt match
    case S(x) => f(x)((p, ctx) => optionSome(p)(k(_, ctx)))
    case N => optionNone()(k(_, summon))

  // instrumentation rules

  def ruleEnd(symName: String = "end")(k: Path => Block): Block =
    blockCtor("End", Ls(), symName)(k)

  def ruleBranches(x: Path, p: Path, arms: Ls[Case -> Block], dflt: Opt[Block], symName: String = "branches")(using Context)(k: (Path, Context) => Block): Block =
    def applyRuleBranch(cse: Case, block: Block)(f: Path => Context => Block)(ctx: Context): Block =
      transformCase(cse): cse =>
        transformBlock(block)(using ctx.addCache(p, x)): (y, ctx) =>
          blockCtor("Arm", Ls(cse, y)): cde =>
            f(cde)(ctx.delCache(p))

    (arms.map(applyRuleBranch).collectApply(_: Ls[Path] => Context => Block)(summon)): arms =>
      ctx =>
        tuple(arms): arms =>
          ruleEnd(): e =>
            def dfltStaged(k: (Path, Context) => Block) = dflt match
              case S(dflt) =>
                transformBlock(dflt)(using ctx.addCache(p, x)): (dflt, ctx) =>
                  optionSome(dflt)(k(_, ctx.delCache(p)))
              case N => optionNone()(k(_, ctx))
            dfltStaged: (dflt, ctx) =>
              blockCtor("Match", Ls(x, arms, dflt, e), symName)(k(_, ctx))

  // transformations of Block

  def transformPath(p: Path)(using ctx: Context)(k: (Path, Context) => Block): Block =
    // rulePath
    ctx.getCache(p).map(k(_, ctx)).getOrElse:
      p match
        case Value.Ref(l, disamb) =>
          transformSymbol(disamb.getOrElse(l)): (sym, ctx) =>
            blockCtor("ValueRef", Ls(sym), "var")(k(_, ctx))
        case l: Value.Lit =>
          blockCtor("ValueLit", Ls(l), "lit")(k(_, ctx))
        case s @ Select(p, Tree.Ident(name)) =>
          transformPath(p): (x, ctx) =>
            s.symbol match
              case S(sym) => transformSymbol(sym, true, pOpt = S(s))(using ctx)((sym, ctx) => blockCtor("Select", Ls(x, sym), "sel")(k(_, ctx)))
              case N => blockCtor("Symbol", Ls(toValue(name)))(sym => blockCtor("Select", Ls(x, sym), "sel")(k(_, ctx)))
        case DynSelect(qual, fld, arrayIdx) =>
          transformPath(qual): (x, ctx) =>
            transformPath(fld)(using ctx): (y, ctx) =>
              blockCtor("DynSelect", Ls(x, y, toValue(arrayIdx)), "dynsel")(k(_, ctx))
        case _: Value.This =>
          raise(ErrorReport(msg"Value.This not supported in staged module." -> p.toLoc :: Nil))
          End()

  def transformResult(r: Result)(using ctx: Context)(k: (Path, Context) => Block): Block = r match
    case p: Path => transformPath(p)(k)
    case Tuple(mut, elems) =>
      if mut then raise(ErrorReport(msg"Mutable tuples not supported in staged module." -> r.toLoc :: Nil))
      transformArgs(elems): (xs, ctx) =>
        tuple(xs.map(_._1)): codes =>
          blockCtor("Tuple", Ls(codes), "tup")(k(_, ctx))
    case Instantiate(mut, cls, args) =>
      if mut then raise(ErrorReport(msg"Mutable instantiations not supported in staged module." -> r.toLoc :: Nil))
      transformArgs(args): (xs, ctx) =>
        transformPath(cls)(using ctx): (cls, ctx) =>
          tuple(xs.map(_._1)): codes =>
            blockCtor("Instantiate", Ls(cls, codes), "inst")(k(_, ctx))
    // desugar Runtime.Tuple.get into Select
    case Call(fun, Ls(Arg(_, scrut), Arg(_, Value.Lit(Tree.IntLit(idx))))) if fun == State.runtimeSymbol.asPath.selSN("Tuple").selSN("get") =>
      transformPath(Select(scrut, Tree.Ident(idx.toString()))(N))(k)
    case Call(fun, args) =>
      transformPath(fun): (stagedFun, ctx) =>
        transformArgs(args)(using ctx): (args, ctx) =>
          tuple(args.map(_._1)): tup =>
            blockCtor("Call", Ls(stagedFun, tup), "app")(k(_, ctx))
    case _ =>
      raise(ErrorReport(msg"Other Results not supported in staged module: ${r.getClass.toString()}" -> r.toLoc :: Nil))
      End()

  def transformArg(a: Arg)(using Context)(k: ((Path, Bool), Context) => Block): Block =
    val Arg(spread, value) = a
    if spread.isDefined then raise(ErrorReport(msg"Spread parameters are not supported in staged module." -> value.toLoc :: Nil))
    transformPath(value): (value, ctx) =>
      blockCtor("Arg", Ls(value)): cde =>
        k((cde, spread.isDefined), ctx)

  def transformArgs(args: Ls[Arg])(using Context)(k: (Ls[(Path, Bool)], Context) => Block): Block =
    args.map(a => ctx => transformArg(a)(using ctx)).chainContext(k)

  // maintain parameter names in instrumented code
  def transformParamList(ps: ParamList)(using ctx: Context)(k: (Path, Context) => Block) =
    ps.params.map(p => ctx => transformSymbol(p.sym, true)(using ctx)).chainContext((ps, ctx) => tuple(ps)(k(_, ctx)))

  def transformParamsOpt(pOpt: Opt[ParamList])(using ctx: Context)(k: (Path, Context) => Block) =
    transformOption(pOpt, transformParamList)(k)

  def transformParams(params: Ls[ParamList])(using Context)(k: (Path, Context) => Block) =
    params.map(ps => ctx => transformParamList(ps)(using ctx)).chainContext((p, ctx) => tuple(p)(k(_, ctx)))

  def transformCase(cse: Case)(using Context)(k: Path => Block): Block = cse match
    case Case.Lit(lit) => blockCtor("Lit", Ls(Value.Lit(lit)))(k)
    case Case.Cls(cls, path) =>
      transformSymbol(cls): (cls, ctx) =>
        transformPath(path)(using ctx): (path, ctx) =>
          blockCtor("Cls", Ls(cls, path))(k)
    case Case.Tup(len, inf) =>
      if inf then raise(ErrorReport(msg"Spread parameters are not supported in staged module: ${cse.toString()}" -> N :: Nil))
      blockCtor("Tup", Ls(toValue(len)))(k)
    case Case.Field(name, safe) =>
      raise(ErrorReport(msg"Case.Field not supported in staged module." -> name.toLoc :: Nil))
      End()

  def transformBlock(b: Block)(using ctx: Context)(k: (Path, Context) => Block): Block = b match
    case Return(res, implct) =>
      transformResult(res): (x, ctx) =>
        blockCtor("Return", Ls(x, toValue(implct)), "return")(k(_, ctx))
    case Assign(x, r, b) =>
      transformSymbol(x): (xSym, ctx) =>
        blockCtor("ValueRef", Ls(xSym)): xStaged =>
          (Assign(x, xStaged, _)):
            transformResult(r)(using ctx.addCache(x.asPath, xStaged)): (y, ctx) =>
              transformBlock(b)(using ctx): (z, ctx) =>
                blockCtor("Assign", Ls(xSym, y, z), "assign")(k(_, ctx))
    case Define(cls: ClsLikeDefn, rest) =>
      assert(cls.companion.isEmpty, "nested module not supported")
      transformSymbol(cls.isym): (c, ctx) =>
        // staging the methods within the module
        cls.methods.map(defn => ctx => transformFunDefn(defn)(using ctx)).chainContext(using ctx): (methods, ctx) =>
          tuple(methods): methods =>
            optionNone(): none => // TODO: handle companion object
              blockCtor("ClsLikeDefn", Ls(c, methods, none)): cls =>
                transformBlock(rest)(using ctx): (p, ctx) =>
                  blockCtor("Define", Ls(cls, p))(k(_, ctx))
    case Define(v: ValDefn, rest) =>
      // TODO: only allow ValDefn inside ctors
      transformOption(v.tsym.owner, transformSymbol(_)): (owner, ctx) =>
        transformSymbol(v.sym)(using ctx): (sym, ctx) =>
          transformPath(v.rhs)(using ctx): (rhs, ctx) =>
            transformBlock(rest)(using ctx): (p, ctx) =>
              blockCtor("ValDefn", Ls(owner, sym, rhs)): v =>
                blockCtor("Define", Ls(v, p))(k(_, ctx))
    case End(_) => ruleEnd()(k(_, ctx))
    case Match(p, ks, dflt, rest) =>
      transformPath(p): (x, ctx) =>
        ruleBranches(x, p, ks, dflt)(using ctx): (stagedMatch, ctx) =>
          transformBlock(rest)(using ctx): (z, ctx) =>
            fnConcat(stagedMatch, z, "match")(k(_, ctx))
    case Begin(sub, rest) =>
      // TODO: This is untested as there is no test case that generates the Begin block yet
      transformBlock(sub): (sub, ctx) =>
        transformBlock(rest)(using ctx): (rest, ctx) =>
          fnConcat(sub, rest)(k(_, ctx))
    case Scoped(syms, body) =>
      syms.toList.sortBy(_.uid).map(s => ctx => transformSymbol(s)(using ctx)).chainContext(using ctx): (symsStaged, ctx) =>
        tuple(symsStaged): tup =>
          transformBlock(body)(using ctx): (body, ctx) =>
            blockCtor("Scoped", Ls(tup, body))(b => Scoped(syms, k(b, ctx)))
    case Define(_: FunDefn, _) =>
      raise(ErrorReport(msg"Nested function definitions are not supported in staged modules. Try enabling :ftc." -> N :: Nil))
      End()
    case _: Label | _: Break =>
      raise(ErrorReport(msg"Other Blocks not supported in staged module: ${b.getClass.toString()}." -> N :: Nil))
      End()
    case _ =>
      raise(ErrorReport(msg"Other Blocks not supported in staged module: ${b.getClass.toString()}" -> N :: Nil))
      End()

  def transformFunDefn(f: FunDefn)(using Context)(k: (Path, Context) => Block): Block =
    // maintain parameter names in instrumented code
    transformSymbol(f.sym): (sym, ctx) =>
      if f.params.length > 1 && !ctx.allowMultipleParamList then
        raise(ErrorReport(msg":ftc must be enabled to desugar functions with multiple parameter lists." -> f.sym.toLoc :: Nil))
      transformParams(f.params)(using ctx): (paramList, ctx) =>
        transformBlock(f.body)(using ctx): (body, ctx) =>
          blockCtor("FunDefn", Ls(sym, paramList, body))(k(_, ctx))

  def stageMethod(f: FunDefn, ctx: Context = Context(new HashMap())): FunDefn =
    val stageSymName = f.sym.nme + "_instr"
    val stageSym = BlockMemberSymbol(stageSymName, Nil, false)

    // turn into fundefn
    val dSym = TermSymbol(f.dSym.k, f.dSym.owner, Tree.Ident(stageSymName))
    val argSyms = f.params.flatMap(_.params).map(_.sym)
    val newBody =
      val rest = transformFunDefn(f)(using ctx)((block, _) => Return(block, false))
      (Scoped(Set(argSyms*), rest))

    FunDefn.withFreshSymbol(f.dSym.owner, stageSym, Ls(PlainParamList(Nil)), newBody)(false, f.configOverride)

  def refreshParamList(ps: ParamList) = 
    PlainParamList(ps.params.map(p => Param.simple(VarSymbol(Tree.Ident(p.sym.nme)))))

  def genMethod(cache: Path, classFun: Bool)(f: FunDefn, stagedPath: Path) =
    val genSymName = f.sym.nme + "_gen"
    val sym = BlockMemberSymbol(genSymName, Nil, false)
    val dSym = TermSymbol(f.dSym.k, f.dSym.owner, Tree.Ident(genSymName))

    // refresh parameters
    val funParams = f.params.map(refreshParamList)
    val params = if classFun then PlainParamList(Param.simple(VarSymbol(Tree.Ident("cls"))) :: Nil) :: funParams else funParams
    val body = params.map(ps => tuple(ps.params.map(_.sym))).collectApply: tups =>
      tuple(tups): args =>
        call(helperMod("specialize"), Ls(cache, toValue(f.sym.nme), stagedPath, args)): res =>
          Return(res, false)
    FunDefn.withFreshSymbol(f.dSym.owner, sym, params, body)(false, f.configOverride)
  
  def stageCtor(ctorFun: FunDefn): FunDefn = 
    // refresh VarSymbols for ctor
    val paramSymMap = ctorFun.params.map(_.params.map(x => x.sym -> VarSymbol(x.sym.id))).flatten.toMap
    val transformer = new BlockTransformer(new SymbolSubst():
      // refresh symbols after copying parameter list
      override def mapVarSym(l: VarSymbol): VarSymbol = paramSymMap.getOrElse(l, l)
    ):
      override def applyBlock(b: Block) = b match
        // process ctor: remove ValDefn of parameters already defined in the class parameters
        // remove `val C.x = x` statements from the constructor
        case Define(ValDefn(_, _, Value.Ref(sym: VarSymbol, _)), rest)
          if paramSymMap.contains(sym) => applyBlock(rest)
        case _ => super.applyBlock(b)
    stageMethod(transformer.applyFunDefn(ctorFun), Context(new HashMap(), true))
    

  def stageMethods(ownerSym: DefinitionSymbol[?], modSym: InnerSymbol, forClass: Bool, cacheNme: Str, generatorMapNme: Str)(methods: Ls[FunDefn]): (FunDefn, Ls[FunDefn], Block => Block) =
    // for storing specialized functions in each staged module
    val cacheSym = BlockMemberSymbol(cacheNme, Nil, true)
    val cacheTsym = TermSymbol(syntax.ImmutVal, S(modSym), Tree.Ident(cacheNme))
    val cachePath = modSym.asPath.selSN(cacheNme)
    val generatorMapSym = BlockMemberSymbol(generatorMapNme, Nil, true)
    val generatorMapTsym = TermSymbol(syntax.ImmutVal, S(modSym), Tree.Ident(generatorMapNme))

    // TODO: remove generator function for ctor, we only need the staged function
    val (stagedMethods, generatorMethods, generatorEntries) = methods.map(f =>
      val staged = stageMethod(f)
      val stagedPath = modSym.asPath.selSN(staged.sym.nme)
      val gen = genMethod(cachePath, forClass)(f, stagedPath)

      (
        staged,
        gen,
        tuple(Ls(toValue(f.sym.nme), modSym.asPath.selSN(gen.sym.nme)))
      )
    ).unzip3

    // initialize cache for the module
    def cacheDecl(rest: Block) =
      val pOpt = if !forClass then S(Value.Ref(ownerSym)) else N
      
      transformSymbol(ownerSym, pOpt = pOpt)(using Context(new HashMap())): (stagedSym, _) =>
        ctor(State.globalThisSymbol.asPath.selSN("Map"), Nil): map =>
          ctor(helperMod("FunCache"), Ls(stagedSym, map)): funCache =>
            Define(ValDefn(cacheTsym, cacheSym, funCache)(N), rest)

    def generatorMapDecl(rest: Block) =
      generatorEntries.collectApply: defs =>
        tuple(defs): tup =>
          ctor(State.globalThisSymbol.asPath.selSN("Map"), Ls(tup)): map =>
            Define(ValDefn(generatorMapTsym, generatorMapSym, map)(N), rest)
    
    def genOutputBody(sourceSym: VarSymbol, psym: VarSymbol) =
      val options = Record(false, Ls(RcdArg(S(toValue("indent")), toValue(true))))

      call(State.shapeSetSymbol.asPath.selSN("mkDyn"), Nil, isMlsFun = true, symName = "tmp_dyn"): dynVal =>
        def callGenCont(rest: Block) =
          generatorMethods.foldRight(rest)((gen, rest) =>
            val genPath = modSym.asPath.selSN(gen.sym.nme)
            val params = gen.params.map(_.params.map(_ => dynVal))
            params.foldRight((_: Path) => rest)
              ((args, k) => call(_, args, true, "gen_call")(k))
              (genPath)
          )
        callGenCont(call(blockMod("codegen"), toValue(modSym.nme) :: cachePath :: sourceSym.asPath :: psym.asPath :: Nil, true, "tmp")(_ => End()))

    val entryFunDef =
      val sym = BlockMemberSymbol("generate", Nil)
      val sourceSym = VarSymbol(Ident("source"))
      val psym = VarSymbol(Ident("path"))
      val params = PlainParamList(Param.simple(sourceSym) :: Param.simple(psym) :: Nil)
      FunDefn.withFreshSymbol(S(modSym), sym, params :: Nil, genOutputBody(sourceSym, psym))(false, N)

    (entryFunDef, stagedMethods ++ generatorMethods, b => cacheDecl(generatorMapDecl(b)))

  override def applyObjBody(companion: ClsLikeBody) = companion.isym.defn match
    // staged modules
    case S(defn) if defn.hasStagedModifier.isDefined =>
      val (sym, ctor, methods) = (companion.isym, companion.ctor, companion.methods)
      // avoid name clash of cache and generator map for derived staged classes
      val modSym = sym
      val suffix = "$" + sym.nme
      val cacheNme = "cache" + suffix
      val generatorMapNme = "generatorMap" + suffix
      val ctorFun = FunDefn.withFreshSymbol(S(modSym), BlockMemberSymbol("ctor$", Nil, false), Ls(PlainParamList(Nil)), ctor)(false, N)

      val (entryFun, newMethods, cont) = stageMethods(companion.isym, modSym, false, cacheNme, generatorMapNme)(methods)
      companion.copy(
        methods = entryFun :: stageCtor(ctorFun) :: newMethods,
        ctor = Begin(companion.ctor, cont(End())),
      )
    case b => super.applyObjBody(companion)

  override def applyBlock(b: Block): Block = b match
    // staged classes
    case Define(defn: ClsLikeDefn, rest) if defn.isym.defn.exists(_.hasStagedModifier.isDefined) => 
      if !defn.privateFields.isEmpty then
        raise(ErrorReport(msg"Staged classes with private fields are not supported." -> defn.sym.toLoc :: Nil))
        return End()
      
      // stage the companion module first, to avoid staging the new functions we add to the companion module
      val companion = defn.companion.map(applyObjBody).getOrElse(ClsLikeBody.empty(Tree.Ident(defn.sym.nme)))
      
      def replaceSuper(parentPath: Path) = new BlockTransformer(SymbolSubst.Id):
        override def applyResult(r: Result)(k: Result => Block) = super.applyResult(r):
          case Call(Value.Ref(sym: BuiltinSymbol, _), args) if sym.nme == "super" => k(Call(parentPath, args)(true, false, false))
          case r => k(r)
      val preCtor = defn.parentPath match
        case S(parent) => replaceSuper(parent).applyBlock(defn.preCtor)
        case N => defn.preCtor
      
      val (sym, ctor, ctorParams, methods) =
        val ctorParams = defn.paramsOpt match
          case S(ps) => ps :: defn.auxParams
          case N => defn.auxParams
        (defn.sym, defn.ctor, ctorParams, defn.methods)
      
      val modSym = companion.isym
      val suffix = "$" + sym.nme
      val cacheNme = "class$cache" + suffix
      val generatorMapNme = "class$generatorMap" + suffix

      val preCtorFun = FunDefn.withFreshSymbol(S(modSym), BlockMemberSymbol("preCtor$", Nil, false), Ls(PlainParamList(Nil)), preCtor)(false, N)
      val ctorFun = FunDefn.withFreshSymbol(S(modSym), BlockMemberSymbol("class$ctor$", Nil, false), ctorParams, ctor)(false, N)
      
      val (entryFun, newMethods, cont) = stageMethods(defn.isym, modSym, true, cacheNme, generatorMapNme)(methods)
      val (companionEntryFun, companionMethods) = companion.methods.partition(_.sym.nme == "generate")
      val combinedEntryFun: FunDefn = companionEntryFun match
        case Nil => entryFun
        case companionFun :: Nil =>
          val symMap = entryFun.params.flatMap(_.params.map(_.sym))
            .zip(companionFun.params.flatMap(_.params.map(_.sym)))
            .toMap
          val transformer = new BlockTransformer(new SymbolSubst():
            override def mapVarSym(l: VarSymbol): VarSymbol = symMap.getOrElse(l, l)
          )
          val combinedBody = Begin(companionFun.body, transformer.applyBlock(entryFun.body))
          companionFun.copy(body = combinedBody)(companionFun.forceTailRec, companionFun.configOverride)
        case _ =>
          raise(ErrorReport(msg"There shouldn't be more than one entry function generated in a module." -> N :: Nil))
          entryFun
  
      // used for staging classes inside modules
      val newCompanion = companion.copy(
        // actually, the entry function should come from stageMethods
        methods = combinedEntryFun :: stageMethod(preCtorFun) :: stageCtor(ctorFun) :: newMethods ++ companionMethods,
        ctor = Begin(companion.ctor, cont(End())),
      )
      val newClsLikeDefn = defn.copy(companion = S(newCompanion))(defn.configOverride)
      Define(newClsLikeDefn, applyBlock(rest))
    case b => super.applyBlock(b)

  def mkDefnMap(b: Block): Unit =
    val transformer = new BlockTraverser:
      override def applyDefn(defn: Defn) = defn match
        case c: ClsLikeDefn =>
          defnMap.addOne(c.isym, c)
          super.applyDefn(defn)
        case _ => super.applyDefn(defn)
    transformer.applyBlock(b)

  def apply(b: Block) =
    mkDefnMap(b)
    val rest = applyBlock(b)
    symbolMapSym match
      case S(sym) => 
        val mapPath = State.globalThisSymbol.asPath.selSN("Map")
        ctor(mapPath, Nil): map1 =>
          ctor(mapPath, Nil): map2 =>
            ctor(blockMod("SymbolMap"), Ls(map1, map2)): map => 
              Scoped(Set(sym), Assign(sym, map, rest))
      case N => rest
